name: Build and Deploy Function App with Infrastructure

on:
  push:
    branches:
      - main 
  workflow_dispatch:

env:
  # === Resource Configuration ===
  AZURE_RESOURCE_GROUP: 'pzachrg'                 # Your target resource group name
  AZURE_LOCATION: 'Canada East'                  # Your target Azure region (should match parameters file)
  FUNCTIONAPP_NAME: 'pzachcomfn'             # Base name for Function App (MUST match value in parameters file)

  # === Code Configuration ===
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'           # Path to your function app code root
  PYTHON_VERSION: '3.11'                        # Python version for build environment

  # === Infrastructure Paths ===
  INFRA_TEMPLATE_PATH: './infra/azuredeploy.json'
  INFRA_PARAMETERS_PATH: './infra/azuredeploy.parameters.json'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: functionapp-artifact-${{ github.run_number }}
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies Using Pip
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: Archive Function App Artifact
      uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        name: functionapp-artifact-${{ github.run_number }}
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Use Service Principal credentials

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ${{ env.INFRA_TEMPLATE_PATH }}
        parameters: ${{ env.INFRA_PARAMETERS_PATH }}
        failOnStdErr: false
        deploymentMode: Incremental # Safest mode

    - name: Logout from Azure
      run: |
        az logout
        az cache purge
        az account clear

  deploy_code:
    runs-on: ubuntu-latest
    needs: [build, deploy_infrastructure] # Wait for build artifact AND infra deployment
    environment: dev

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifact_name }}
        path: ./deploy_package

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Use Service Principal credentials

    - name: Deploy Function App Code
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTIONAPP_NAME }}
        package: ./deploy_package
        scm-do-build-during-deployment: false
        enable-oryx-build: false

    - name: Logout from Azure
      run: |
        az logout
        az cache purge
        az account clear